project_id = "cavrkwzwlgrstddykpsu"

[functions.export-storage-centre]
verify_jwt = true

[functions.create-payroll-record]
verify_jwt = true

[functions.delete-payroll-record]
verify_jwt = true

[functions.approve-payroll-record]
verify_jwt = true

[functions.employee-confirm-payroll]
verify_jwt = true

[functions.employee-dispute-payroll]
verify_jwt = true

[functions.resolve-payroll-dispute]
verify_jwt = true

[functions.send-invitation-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.translate-holidays]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
